### ISSUE TITLE
Flag "x" does not work.

### ISSUE THREAD

**Issue by drakea** [posixninja/ideviceactivate#1]
When I use the x flag, to deactivate my device, it does not deactivate it, even on reboot.

**Comment by posixninja** [comment]
it doesn't work on ipod 3.x, does on 4.x for some reason (looking into it)

**Comment by martinlc** [comment]
Does it work on iphone 3G with iOS4 GM seed? How can I use the source code? I built successfully the app on ubuntu. But, when I click on the app, nothing happened.

**Comment by drakea** [comment]
It's a command line app. So like open a terminal, say the binary is in ur home directory, run this. 

"cd
./ideviceactivate [with the proper flags and arguments, to see them use the h flag]"
it'll work.

**Comment by drakea** [comment]
Hit enter after cd. Then enter after the ./ideviceactivate it didn't place my return keys in my response to you.
