### ISSUE TITLE
Unable to get ActivationInfo from lockdownd

### ISSUE THREAD

**Issue by Wizza785** [posixninja/ideviceactivate#19]
I have been trying to get an iPhone 11 to active and so far haven't had any luck. I looked up this error message and the 2 results were about iCloud locked phones (which does NOT apply to me). Here is the output from `ideviceinfo`

`ActivationState: Unactivated
BasebandActivationTicketVersion: V2
BasebandCertId: 524245983
BasebandChipID: 104
BasebandKeyHashInformation: 
 AKeyStatus: 64
 SKeyStatus: 2
BasebandMasterKeyHash: 1B41607650EBF11C6B39F41CB267DC64C121A9BCF44DBA5D28F55ACC86361BBA366554CD57B4C466055803E1EF81C870
BasebandRegionSKU: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
BasebandSerialNumber: BDvURUej7tYAAAAA
BasebandStatus: BBInfoAvailable
BasebandVersion: 1.01.19
BluetoothAddress: 88:64:40:82:25:15
BoardId: 4
BrickState: true
BuildVersion: 17A878
CPUArchitecture: arm64e
CarrierBundleInfoArray[1]: 
 0: 
  CFBundleIdentifier: com.apple.Verizon_LTE_US
  CFBundleVersion: 38.0.1
  GID1: bae0000000000000
  GID2: ffffffffffffffff
  IntegratedCircuitCardIdentity: 89148000001724245476
  InternationalMobileSubscriberIdentity: 311480174000504
  MCC: 311
  MNC: 480
  MobileEquipmentIdentifier: 35397810166334
  SIMGID1: uuAAAAAAAAA=
  SIMGID2: //////////8=
  Slot: kOne
  kCTPostponementInfoAvailable: DefaultCarrierInfo
CertID: 524245983
ChipID: 32816
ChipSerialNo: BDvURUej7tYAAAAA
DeviceClass: iPhone
DeviceColor: 1
DeviceName: iPhone
DieID: 4817871214510126
EthernetAddress: 88:64:40:7c:d9:fe
FirmwareVersion: iBoot-5540.0.129
FusingStatus: 3
GID1: bae0000000000000
GID2: ffffffffffffffff
HardwareModel: N104AP
HardwarePlatform: t8030
HasSiDP: true
HostAttached: true
IntegratedCircuitCardIdentity: 89148000001724245476
InternationalMobileEquipmentIdentity: 353978101663342
InternationalMobileEquipmentIdentity2: 353978101682573
InternationalMobileSubscriberIdentity: 311480174000504
InternationalMobileSubscriberIdentityOverride: false
MLBSerialNumber: F3X935504DEL73W4
MobileEquipmentIdentifier: 35397810166334
MobileSubscriberCountryCode: 311
MobileSubscriberNetworkCode: 480
ModelNumber: MWL82
NonVolatileRAM: 
 auto-boot: dHJ1ZQ==
 backlight-level: MTQxNw==
 boot-args: 
 bootdelay: MA==
 usbcfwflasherResult: Tm8gZXJyb3Jz
PRIVersion_Major: 0
PRIVersion_Minor: 0
PRIVersion_ReleaseNo: 17
PartitionType: GUID_partition_scheme
PasswordProtected: false
PhoneNumber: +1 (858) 437-2599
PkHash: Hz9b38WSRX/cE6qam0xEfaM6v7nHw0ZdWjTPu2WOXVU=
ProductName: iPhone OS
ProductType: iPhone12,1
ProductVersion: 13.1.3
ProductionSOC: true
ProtocolVersion: 2
ProximitySensorCalibration: f3oABTIAHgDqJ1dBq9IwQgAAyELN0i1Bg2tJQgAAFkPN0i1Bg2tJQgAAFkNBXphCYMyswFenuUSSm7lEfji4RHAzt0QYWqZBabGsQed4zkEs29NBAAAgQocUHUOTM+hBAABIQsKu0UN1DNFDfTcHRi6MdUO5OG9dASAYGsQgnEVhf59D5z1IRQIAAAAAAAA3
RegionInfo: LL/A
SIM1IsEmbedded: false
SIMGID1: uuAAAAAAAAA=
SIMGID2: //////////8=
SIMStatus: kCTSIMSupportSIMStatusReady
SIMTrayStatus: kCTSIMSupportSIMTrayInsertedWithSIM
SerialNumber: FK1ZC49BN72K
SoftwareBehavior: EQAAAAAAAAAAAAAAAAAAAA==
SoftwareBundleVersion: 
SupportedDeviceFamilies[1]: 
 0: 1
TelephonyCapability: true
TimeIntervalSince1970: 1571710257.073983
TimeZone: America/Los_Angeles
TimeZoneOffsetFromUTC: -25200.000000
TrustedHostAttached: true
UniqueChipID: 4817871214510126
UniqueDeviceID: 00008030-00111DD40E50802E
UntrustedHostBUID: 4E968405-F245-2D25-057F-BEA506FDF3B9
UseRaptorCerts: true
Uses24HourClock: false
WiFiAddress: 88:64:40:78:9d:01
WirelessBoardSerialNumber: 9E22101007
kCTPostponementInfoPRIVersion: 0.0.17
kCTPostponementInfoServiceProvisioningState: true
kCTPostponementStatus: kCTPostponementStatusReady
`
It is also worth mentioning when using the "Quick Start" feature, it hangs on `Waiting for Other iPhone`

Again the device is NOT iCloud locked. 
Any help would be great!

Thank you!

**Comment by Valehero** [comment]
You will NOT be able to Activate this iPhone since its blocked by Apple.

A report for this iPhone shows:

Device: iPhone 11 White 64GB
Model: A-2111 US/Canada
IMEI Number: 353978101663342
IMEI2 Number: 353978101682573
Serial Number: FK1ZC49BN72K
Manufacture Date: 04 Sep 2019
Unit Age: 1 month and 18 days
Assembled In: Foxconn Zhengzhou, China
Find My iPhone: OFF
iCloud Mode: NA
MDM-Enrolled: False
Next Policy ID: 2365
Carrier: Chimaera Device Policy
SIM-Lock: Locked
--

NOTE: "Chimaera Device Policy" means this iPhone IMEI is BLOCKED by Apple.
Get another iPhone.

**Comment by Wizza785** [comment]
Welp I got scammed-ish. My friend gave me the phone. Sry to waste ur time but thx for the help!

**Comment by Wizza785** [comment]
Welp I got scammed-ish. My friend gave me the phone. Sry to waste ur time but thx for the help!

**Comment by pedroadelino** [comment]
> You will NOT be able to Activate this iPhone since its blocked by Apple.
> 
> A report for this iPhone shows:
> 
> ## Device: iPhone 11 White 64GB
> Model: A-2111 US/Canada
> IMEI Number: 353978101663342
> IMEI2 Number: 353978101682573
> Serial Number: FK1ZC49BN72K
> Manufacture Date: 04 Sep 2019
> Unit Age: 1 month and 18 days
> Assembled In: Foxconn Zhengzhou, China
> Find My iPhone: OFF
> iCloud Mode: NA
> MDM-Enrolled: False
> Next Policy ID: 2365
> Carrier: Chimaera Device Policy
> SIM-Lock: Locked
> NOTE: "Chimaera Device Policy" means this iPhone IMEI is BLOCKED by Apple.
> Get another iPhone.

Which website did you use to get that report?
