### ISSUE TITLE
How to install ideviceactivate

### ISSUE THREAD

**Issue by ebitsdev** [posixninja/ideviceactivate#3]
Hello posixninja,

I am trying to install ideviceactivate but don't know how to proceed. Would you please let me know how to install it?

I have all the other utilities installed (libimobiledevice, sbmanager, ideviceinstaller...)

Thank you.

**Comment by ebitsdev** [comment]
I get the following when I try to: make install
make: **\* No rule to make target `install'.  Stop.

**Comment by ravomavain** [comment]
I think you can simply use this command :
sudo install src/ideviceactivate /usr/local/bin

**Comment by ebitsdev** [comment]
Thanks a lot ravomavain. Got it installed. Will now test it and see how it goes.

**Comment by boxingsquirrel** [comment]
For anyone wondering, there is now an install target in the Makefile. You should use that to install.

**Comment by lamtran84** [comment]
Hello posixninja,

I am Lam Tran,
Current, I am working with Ubuntu OS 10.04. I downloaded and used your ideviceactivate package. I activated success with iPhone 2G, 3G, 3GS, 4G and iPod Touch 2G, 3G, 4G, but with iPod Touch 1G, after execute then returned result is SUCCESS but device not activate.
I expect support from you,

Thank you for all,
Lam Tran
Email: lamtv84@yahoo.com

**Comment by ebitsdev** [comment]
No longer needed.

**Comment by shawn7226791** [comment]
hey can you help im trying to intsall it and i get this
/usr/bin/ld: cannot find -lgthread-2.0
/usr/bin/ld: cannot find -lgnutls
/usr/bin/ld: cannot find -ltasn1
/usr/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:5: all] Error 1
make[1]: Leaving directory '/root/Downloads/idevicerestore/ideviceactivate/src'
make: *** [Makefile:2: all] Error 2
